name: p2p_exercise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip:
      - accelerate==1.1.1
      - diffusers==0.31.0
      - ftfy==6.3.1
      - huggingface-hub==0.26.3
      - ipywidgets==8.1.5
      - jupyterlab-widgets==3.0.13
      - numpy==2.1.3
      - opencv-python==4.10.0.84
      - pillow==11.0.0
      - torch==2.4.1
      - transformers==4.46.3
